version: "3"

services:
  chat_gpt:
    # todo image之后修改,目前用之前的镜像
    image: qh_search:latest
    container_name: my_gpt
    restart: always
    ports:
        - "8088:8088"
    networks:
      - docker_public_network
    volumes:
      - './log:/root/log:rw'
      - '/etc/localtime:/etc/localtime'
    command: python3 chat_gpt/main.py

networks:
    docker_public_network:
        external: true